package com.weatherapp.dto.city.embeded;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

@JsonIgnoreProperties(ignoreUnknown = true)
@Data
@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
public class LocalNames {
    public String ta;
    public String be;
    public String tk;
    public String qu;
    public String fa;
    public String fi;
    public String cu;
    public String an;
    public String zh;
    public String ln;
    public String kk;
    public String yi;
    public String jv;
    public String kl;
    public String br;
    public String ro;
    public String tr;
    public String bi;
    public String ie;
    public String ch;
    public String it;
    public String th;
    public String lg;
    public String os;
    public String ur;
    public String yo;
    public String co;
    public String iu;
    public String lt;
    public String kg;
    public String pl;
    public String ps;
    public String mi;
    public String el;
    public String gv;
    public String st;
    public String zu;
    public String ko;
    public String uz;
    public String am;
    public String hr;
    public String sl;
    public String mn;
    public String tt;
    public String et;
    public String dz;
    public String bn;
    public String mk;
    public String gd;
    public String la;
    public String ga;
    public String ay;
    public String av;
    public String ak;
    public String he;
    public String ca;
    public String nn;
    public String ht;
    public String hu;
    public String ku;
    public String lv;
    public String so;
    public String gl;
    public String mg;
    public String bg;
    public String na;
    public String oc;
    public String az;
    public String ce;
    public String da;
    public String cs;
    public String sm;
    public String ty;
    public String en;
    public String nb;
    public String sh;
    public String ss;
    public String eu;
    public String ja;
    public String su;
    public String cv;
    public String mr;
    public String no;
    public String se;
    public String eo;
    public String fr;
    public String sk;
    public String gn;
    public String ba;
    public String es;
    public String uk;
    public String wa;
    public String feature_name;
    public String cy;
    public String hy;
    public String bo;
    public String ms;
    public String hi;
    public String ru;
    public String za;
    public String sc;
    public String fy;
    public String ia;
    public String kv;
    public String ab;
    public String li;
    public String is;
    public String ml;
    public String mt;
    public String io;
    public String vi;
    public String kw;
    public String bs;
    public String dv;
    public String af;
    public String ascii;
    public String kn;
    public String ar;
    public String sq;
    public String nl;
    public String sr;
    public String tg;
    public String ka;
    public String sw;
    public String my;
    public String fo;
    public String de;
    public String vo;
    public String id;
    public String sg;
    public String te;
    public String wo;
    public String tl;
    public String ug;
    public String pt;
    public String sv;
    public String ky;
}
